name = "ig-gallery-worker"
main = "src/index.ts"
compatibility_date = "2024-02-06"

kv_namespaces = [
    { binding = "IG_TOKENS", id = "9bb37a25ddb74f7690bb0d643582a79d" }
]

[triggers]
crons = ["0 0 * * thu"]
